// Only node.js has this modules stuff?  ES6 whither??
export  {dummy, jr, rotators};


console.log("hellow from BOTTOM");
const dummy =()=>{
	return "I come from bottom JS.";
}

let jr = [
{
	"name": "CamEst thou from an OBJECT in TOP?" ,
	"printableCode": "p r i n n a b l e" ,
	"data1": "nihilWordsQuote",
	"verb": "function(a){return this.a}"
},
{
	"name": "Gramps & Fran",
	"printableCode": "null" ,
	"verb": "function(a){return this.a}"
}
];


let rotators =
[
  {
    "Rk": 1,
    "Pos": "SP",
    "Name": "Jordan Zimmermann\\zimmejo02",
    "Age": 33,
    "W": 0,
    "L": 0,
    "W-L%": "",
    "ERA": 0.66,
    "G": 2,
    "GS": 2,
    "GF": 0,
    "CG": 0,
    "SHO": 0,
    "SV": 0,
    "IP": 13.2,
    "H": 7,
    "R": 1,
    "ER": 1,
    "HR": 0,
    "BB": 1,
    "IBB": 1,
    "SO": 10,
    "HBP": 0,
    "BK": 0,
    "WP": 0,
    "BF": 49,
    "ERA+": 540,
    "FIP": 1.69,
    "WHIP": 0.585,
    "H9": 4.6,
    "HR9": 0,
    "BB9": 0.7,
    "SO9": 6.6,
    "SO/W": 10
  },
  {
    "Rk": 2,
    "Pos": "SP",
    "Name": "Matthew Boyd*\\boydma01",
    "Age": 28,
    "W": 0,
    "L": 1,
    "W-L%": 0,
    "ERA": 3.18,
    "G": 2,
    "GS": 2,
    "GF": 0,
    "CG": 0,
    "SHO": 0,
    "SV": 0,
    "IP": 11.1,
    "H": 10,
    "R": 5,
    "ER": 4,
    "HR": 0,
    "BB": 4,
    "IBB": 0,
    "SO": 23,
    "HBP": 0,
    "BK": 0,
    "WP": 0,
    "BF": 48,
    "ERA+": 113,
    "FIP": -0.07,
    "WHIP": 1.235,
    "H9": 7.9,
    "HR9": 0,
    "BB9": 3.2,
    "SO9": 18.3,
    "SO/W": 5.75
  },
  {
    "Rk": 3,
    "Pos": "SP",
    "Name": "Matt Moore*\\moorema02",
    "Age": 30,
    "W": 0,
    "L": 0,
    "W-L%": "",
    "ERA": 0,
    "G": 1,
    "GS": 1,
    "GF": 0,
    "CG": 0,
    "SHO": 0,
    "SV": 0,
    "IP": 7,
    "H": 2,
    "R": 0,
    "ER": 0,
    "HR": 0,
    "BB": 1,
    "IBB": 0,
    "SO": 6,
    "HBP": 0,
    "BK": 0,
    "WP": 0,
    "BF": 23,
    "ERA+": "",
    "FIP": 1.64,
    "WHIP": 0.429,
    "H9": 2.6,
    "HR9": 0,
    "BB9": 1.3,
    "SO9": 7.7,
    "SO/W": 6
  },
  {
    "Rk": 4,
    "Pos": "SP",
    "Name": "Spencer Turnbull\\turnbsp01",
    "Age": 26,
    "W": 0,
    "L": 1,
    "W-L%": 0,
    "ERA": 5.4,
    "G": 1,
    "GS": 1,
    "GF": 0,
    "CG": 0,
    "SHO": 0,
    "SV": 0,
    "IP": 5,
    "H": 4,
    "R": 3,
    "ER": 3,
    "HR": 1,
    "BB": 2,
    "IBB": 0,
    "SO": 5,
    "HBP": 1,
    "BK": 0,
    "WP": 0,
    "BF": 21,
    "ERA+": 69,
    "FIP": 5.33,
    "WHIP": 1.2,
    "H9": 7.2,
    "HR9": 1.8,
    "BB9": 3.6,
    "SO9": 9,
    "SO/W": 2.5
  },
  {
    "Rk": 5,
    "Pos": "SP",
    "Name": "Tyson Ross\\rossty01",
    "Age": 32,
    "W": 0,
    "L": 1,
    "W-L%": 0,
    "ERA": 3.6,
    "G": 1,
    "GS": 1,
    "GF": 0,
    "CG": 0,
    "SHO": 0,
    "SV": 0,
    "IP": 5,
    "H": 4,
    "R": 3,
    "ER": 2,
    "HR": 2,
    "BB": 4,
    "IBB": 0,
    "SO": 4,
    "HBP": 0,
    "BK": 0,
    "WP": 1,
    "BF": 23,
    "ERA+": 104,
    "FIP": 8.93,
    "WHIP": 1.6,
    "H9": 7.2,
    "HR9": 3.6,
    "BB9": 7.2,
    "SO9": 7.2,
    "SO/W": 1
  }
]

/*
CORS notes from Mozilla:
"CORS requests may only use the HTTPS URL scheme, but the URL specified by the request is of a different type. This often occurs if the URL specifies a local file, using a file:/// URL."

"To fix this problem, simply make sure you use HTTPS URLs when issuing requests involving CORS."
*/